### ISSUE TITLE
Get table length and a way to iterate over it

### ISSUE THREAD

**Issue by lurk26** [jeremyong/Selene#102]
I use lua tables to store data in a human-readable format that is loaded by my engine. As such, one of the common operations i need to do is find the length of a table and iterate over it to load all the values. A simplified version of one of my files may look like this:
```lua

return
{
	vertices =
	{
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		{	pos	= { x, y, z}, rgba = { red, green , blue, alpha }	},
		
	}
}

```

How can I use Selene to iterate over the vertices table? As this is a generated data file, I cannot have any functions in it.

Sorry if I overlooked something while reading the docs..

**Comment by jeremyong** [comment]
I would provide this function in Lua and call it from Selene.
