### ISSUE TITLE
Lua variable to std::string fails on VS2015

### ISSUE THREAD

**Issue by Zardoz89** [jeremyong/Selene#103]
I just try this, that works on gcc 4.9 on my Linux box : 
```
std::string out = lua_state["bar"][3];
_log.info() << "LUA: " << out;
```
Simply crash on VS2015 with Lua 5.2

How ever if I try, calling explicitly std::string conversion operator, it works : 
```
auto sel = lua_state["bar"][3];
std::string out = sel.operator std::string();
log->info() << "LUA: " << out;
```

**Comment by jeremyong** [comment]
Is there a crash error?

**Comment by Zardoz89** [comment]
Exception thrown at 0x010EE486 in TEC.exe: 0xC0000005: Access violation reading location 0x00000014.

![image](https://cloud.githubusercontent.com/assets/888483/10250608/1830924e-692c-11e5-9ca6-999c845b7691.png)

The code that throw the exception is inside on "xstring" lib of VStudio : 
```
	size_type size() const _NOEXCEPT
		{	// return length of sequence
		return (this->_Mysize());
		}
```
Looks that the moment of throwing the exception, the basic_string object isn't correctly initialized -----> Comes from here : 
![image](https://cloud.githubusercontent.com/assets/888483/10250810/584bf6f6-692d-11e5-8db9-e3f26c214db1.png)
Were _MyT is : ```typedef basic_string<_Elem, _Traits, _Alloc> _Myt;```

I usually work with valgrind, kdgb & cia on Linux. I don't know very well VStudio to get more useful information. But, I think that is using the copy constructor instead of building a string from a char array.

**Comment by Zardoz89** [comment]
Merge #101 fix this.
