### ISSUE TITLE
Building in a shared library

### ISSUE THREAD

**Issue by xicoh** [jeremyong/Selene#120]
Hi,

My main usage of Lua is in a shared library used by different programs. As I am investigating whether this is possible, I noticed that at least one function cannot be inlined by the compiler, and thus cannot be used in the library as such. In `include/selene/LuaRef.h`, at line 46, `append_ref_recursive` should be marked `inline` to allow building inside a library while still having access to the headers. Not sure if there are other cases in the library though.

Thanks for the great work!

**Comment by Taronyu** [comment]
Ah, that's the same issue I had when including the headers in multiple cpp files. I created a pull request with the fix.

**Comment by jeremyong** [comment]
Should now be resolved.
