### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by AndrewChicco** [jeremyong/Selene#138]
Hi,
I'm getting some major compilation errors attempting to compile a very simple program
(using Ubuntu 15.x with G++ 4.9.2).

These problems appeared when I added in all the selene specific code in the main function.

Can someone let me know if I'm doing something terribly wrong.

Please excuse my ignorance if I've done something very obviously wrong.

Thanks,
Andrew

#include <selene.h>
#include <iostream>
#include <cassert>

using namespace std;
using namespace sel;

int main()
{
   State state;
   state.Load("./test.lua");
   assert(state["foo"] == 4);
   assert(state["bar"][3] == "hi");
   assert(state["bar"]["key"] == "there");

   // basic checking
   cout << "Hello world!" << endl;
   return 0;
}

-- test.lua
foo = 4
bar = {}
bar[3] = "hi"
bar["key"] = "there"

errors

-------------- Clean: Debug in LUATest (compiler: GNU GCC Compiler)---------------

Cleaned "LUATest - Debug"

-------------- Build: Debug in LUATest (compiler: GNU GCC Compiler)---------------

g++ -Wall -fexceptions -std=c++11 -I/usr/include/lua5.2 -I/usr/include/selene -c /home/andrew/code/LUATest/LUATest/main.cpp -o obj/Debug/main.o
g++  -o bin/Debug/LUATest obj/Debug/main.o   
obj/Debug/main.o: In function `sel::MetatableRegistry::detail::_create_table_in_registry(lua_State*, std::string const&)':
main.cpp:(.text+0x100): undefined reference to `lua_pushlstring'
main.cpp:(.text+0x112): undefined reference to `lua_createtable'
main.cpp:(.text+0x125): undefined reference to `lua_settable'
obj/Debug/main.o: In function `sel::detail::_get(sel::detail::_id<int>, lua_State*, int)':
main.cpp:(.text._ZN3sel6detail4_getENS0_3_idIiEEP9lua_Statei[_ZN3sel6detail4_getENS0_3_idIiEEP9lua_Statei]+0x12): undefined reference to `lua_tointegerx'
obj/Debug/main.o: In function `sel::detail::_get(sel::detail::_id<std::string>, lua_State*, int)':
main.cpp:(.text._ZN3sel6detail4_getENS0_3_idISsEEP9lua_Statei[_ZN3sel6detail4_getENS0_3_idISsEEP9lua_Statei]+0x2c): undefined reference to `lua_tolstring'
obj/Debug/main.o: In function `sel::detail::_push(lua_State*, int)':
main.cpp:(.text._ZN3sel6detail5_pushEP9lua_Statei[_ZN3sel6detail5_pushEP9lua_Statei]+0x10): undefined reference to `lua_pushinteger'
obj/Debug/main.o: In function `sel::detail::_push(lua_State*, std::string const&)':
main.cpp:(.text._ZN3sel6detail5_pushEP9lua_StateRKSs[_ZN3sel6detail5_pushEP9lua_StateRKSs]+0x2e): undefined reference to `lua_pushlstring'
obj/Debug/main.o: In function `sel::test_stored_exception(lua_State*)':
main.cpp:(.text._ZN3sel21test_stored_exceptionEP9lua_State[_ZN3sel21test_stored_exceptionEP9lua_State]+0xf): undefined reference to `lua_isuserdata'
main.cpp:(.text._ZN3sel21test_stored_exceptionEP9lua_State[_ZN3sel21test_stored_exceptionEP9lua_State]+0x3a): undefined reference to `luaL_testudata'
obj/Debug/main.o: In function `sel::ResetStackOnScopeExit::ResetStackOnScopeExit(lua_State*)':
main.cpp:(.text._ZN3sel21ResetStackOnScopeExitC2EP9lua_State[_ZN3sel21ResetStackOnScopeExitC5EP9lua_State]+0x18): undefined reference to `lua_gettop'
obj/Debug/main.o: In function `sel::ResetStackOnScopeExit::~ResetStackOnScopeExit()':
main.cpp:(.text._ZN3sel21ResetStackOnScopeExitD2Ev[_ZN3sel21ResetStackOnScopeExitD5Ev]+0x20): undefined reference to `lua_settop'
obj/Debug/main.o: In function `sel::detail::LuaRefDeleter::operator()(int*) const':
main.cpp:(.text._ZNK3sel6detail13LuaRefDeleterclEPi[_ZNK3sel6detail13LuaRefDeleterclEPi]+0x1b): undefined reference to `luaL_unref'
obj/Debug/main.o: In function `sel::LuaRef::Push(lua_State*) const':
main.cpp:(.text._ZNK3sel6LuaRef4PushEP9lua_State[_ZNK3sel6LuaRef4PushEP9lua_State]+0x24): undefined reference to `lua_rawgeti'
obj/Debug/main.o: In function `sel::Traceback(lua_State*)':
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0x16): undefined reference to `lua_type'
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0x31): undefined reference to `lua_tolstring'
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0x52): undefined reference to `lua_pushstring'
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0x65): undefined reference to `lua_getglobal'
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0x7a): undefined reference to `lua_getfield'
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0x8a): undefined reference to `lua_pushvalue'
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0x9a): undefined reference to `lua_pushinteger'
main.cpp:(.text._ZN3sel9TracebackEP9lua_State[_ZN3sel9TracebackEP9lua_State]+0xb0): undefined reference to `lua_callk'
obj/Debug/main.o: In function `sel::SetErrorHandler(lua_State*)':
main.cpp:(.text._ZN3sel15SetErrorHandlerEP9lua_State[_ZN3sel15SetErrorHandlerEP9lua_State]+0x14): undefined reference to `lua_pushcclosure'
main.cpp:(.text._ZN3sel15SetErrorHandlerEP9lua_State[_ZN3sel15SetErrorHandlerEP9lua_State]+0x22): undefined reference to `lua_gettop'
obj/Debug/main.o: In function `sel::Selector::_get(sel::LuaRef) const':
main.cpp:(.text._ZNK3sel8Selector4_getENS_6LuaRefE[_ZNK3sel8Selector4_getENS_6LuaRefE]+0x26): undefined reference to `lua_gettable'
main.cpp:(.text._ZNK3sel8Selector4_getENS_6LuaRefE[_ZNK3sel8Selector4_getENS_6LuaRefE]+0x39): undefined reference to `lua_absindex'
main.cpp:(.text._ZNK3sel8Selector4_getENS_6LuaRefE[_ZNK3sel8Selector4_getENS_6LuaRefE]+0x4d): undefined reference to `lua_remove'
obj/Debug/main.o: In function `sel::Selector::_check_create_table() const::{lambda()#1}::operator()() const':
main.cpp:(.text._ZZNK3sel8Selector19_check_create_tableEvENKUlvE_clEv[_ZZNK3sel8Selector19_check_create_tableEvENKUlvE_clEv]+0x16): undefined reference to `lua_createtable'
obj/Debug/main.o: In function `sel::Selector::_check_create_table() const':
main.cpp:(.text._ZNK3sel8Selector19_check_create_tableEv[_ZNK3sel8Selector19_check_create_tableEv]+0x55): undefined reference to `lua_type'
main.cpp:(.text._ZNK3sel8Selector19_check_create_tableEv[_ZNK3sel8Selector19_check_create_tableEv]+0x72): undefined reference to `lua_settop'
obj/Debug/main.o: In function `sel::Selector::_traverse() const':
main.cpp:(.text._ZNK3sel8Selector9_traverseEv[_ZNK3sel8Selector9_traverseEv]+0x29): undefined reference to `lua_rawgeti'
obj/Debug/main.o: In function `sel::Selector::_evaluate_function_call(int) const':
main.cpp:(.text._ZNK3sel8Selector23_evaluate_function_callEi[_ZNK3sel8Selector23_evaluate_function_callEi]+0x74): undefined reference to `lua_pushvalue'
main.cpp:(.text._ZNK3sel8Selector23_evaluate_function_callEi[_ZNK3sel8Selector23_evaluate_function_callEi]+0x8b): undefined reference to `lua_copy'
main.cpp:(.text._ZNK3sel8Selector23_evaluate_function_callEi[_ZNK3sel8Selector23_evaluate_function_callEi]+0x9f): undefined reference to `lua_replace'
main.cpp:(.text._ZNK3sel8Selector23_evaluate_function_callEi[_ZNK3sel8Selector23_evaluate_function_callEi]+0x14e): undefined reference to `lua_pcallk'
main.cpp:(.text._ZNK3sel8Selector23_evaluate_function_callEi[_ZNK3sel8Selector23_evaluate_function_callEi]+0x169): undefined reference to `lua_remove'
obj/Debug/main.o: In function `sel::State::State(bool)':
main.cpp:(.text._ZN3sel5StateC2Eb[_ZN3sel5StateC5Eb]+0x5f): undefined reference to `luaL_newstate'
main.cpp:(.text._ZN3sel5StateC2Eb[_ZN3sel5StateC5Eb]+0xa6): undefined reference to `luaL_openlibs'
obj/Debug/main.o: In function `sel::State::~State()':
main.cpp:(.text._ZN3sel5StateD2Ev[_ZN3sel5StateD5Ev]+0x32): undefined reference to `lua_close'
obj/Debug/main.o: In function `sel::State::Load(std::string const&)':
main.cpp:(.text._ZN3sel5State4LoadERKSs[_ZN3sel5State4LoadERKSs]+0x51): undefined reference to `luaL_loadfilex'
main.cpp:(.text._ZN3sel5State4LoadERKSs[_ZN3sel5State4LoadERKSs]+0x84): undefined reference to `lua_tolstring'
main.cpp:(.text._ZN3sel5State4LoadERKSs[_ZN3sel5State4LoadERKSs]+0x163): undefined reference to `lua_tolstring'
main.cpp:(.text._ZN3sel5State4LoadERKSs[_ZN3sel5State4LoadERKSs]+0x243): undefined reference to `lua_pcallk'
main.cpp:(.text._ZN3sel5State4LoadERKSs[_ZN3sel5State4LoadERKSs]+0x26b): undefined reference to `lua_tolstring'
obj/Debug/main.o: In function `sel::State::ForceGC()':
main.cpp:(.text._ZN3sel5State7ForceGCEv[_ZN3sel5State7ForceGCEv]+0x14): undefined reference to `lua_gc'
obj/Debug/main.o: In function `sel::LuaRef sel::make_Ref<std::string const&>(lua_State*, std::string const&)':
main.cpp:(.text._ZN3sel8make_RefIRKSsEENS_6LuaRefEP9lua_StateOT_[_ZN3sel8make_RefIRKSsEENS_6LuaRefEP9lua_StateOT_]+0x2f): undefined reference to `luaL_ref'
obj/Debug/main.o: In function `void sel::Selector::_put<sel::Selector::_check_create_table() const::{lambda()#1}>(sel::Selector::_check_create_table() const::{lambda()#1}) const':
main.cpp:(.text._ZNK3sel8Selector4_putIZNKS0_19_check_create_tableEvEUlvE_EEvT_[_ZNK3sel8Selector4_putIZNKS0_19_check_create_tableEvEUlvE_EEvT_]+0x39): undefined reference to `lua_settable'
main.cpp:(.text._ZNK3sel8Selector4_putIZNKS0_19_check_create_tableEvEUlvE_EEvT_[_ZNK3sel8Selector4_putIZNKS0_19_check_create_tableEvEUlvE_EEvT_]+0x4c): undefined reference to `lua_settop'
obj/Debug/main.o: In function `int sel::detail::_pop<int>(sel::detail::_id<int>, lua_State*)':
main.cpp:(.text._ZN3sel6detail4_popIiEET_NS0_3_idIS2_EEP9lua_State[_ZN3sel6detail4_popIiEET_NS0_3_idIS2_EEP9lua_State]+0x23): undefined reference to `lua_settop'
obj/Debug/main.o: In function `std::string sel::detail::_pop<std::string>(sel::detail::_id<std::string>, lua_State*)':
main.cpp:(.text._ZN3sel6detail4_popISsEET_NS0_3_idIS2_EEP9lua_State[_ZN3sel6detail4_popISsEET_NS0_3_idIS2_EEP9lua_State]+0x39): undefined reference to `lua_settop'
obj/Debug/main.o: In function `sel::LuaRef sel::make_Ref<int const&>(lua_State*, int const&)':
main.cpp:(.text._ZN3sel8make_RefIRKiEENS_6LuaRefEP9lua_StateOT_[_ZN3sel8make_RefIRKiEENS_6LuaRefEP9lua_StateOT_]+0x31): undefined reference to `luaL_ref'
Process terminated with status 1 (0 minute(s), 6 second(s))
50 error(s), 0 warning(s) (0 minute(s), 6 second(s))

**Comment by AnonymousProgrammerLandau** [comment]
It seems your commandline `g++ -o bin/Debug/LUATest obj/Debug/main.o` misses parameters to link the Lua libraries.

**Comment by AndrewChicco** [comment]
Hi AnonymousProgrammerLandau,
Much thanks for the hint. It seems to be all working now.
I was just missing the '-llua5.2' for the linking stage.

Andrew
