### ISSUE TITLE
Can't distinguish between nil variables (that don't exist) and default values 

### ISSUE THREAD

**Issue by jeremyherbert** [jeremyong/Selene#58]
It seems unclear to me as to how to deal with variables that do not exist in the lua state. This combined with issue #41 means that lots of things can go bad without the user being informed. I think the correct behaviour here would be an exception, as `int` cannot be NULL. However it has been noted in #10 that exceptions are not going to be used so I am not sure how to proceed.

```
$ lua
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> print(y)
nil
>
```
## 

```
#include "Selene/include/selene.h"
#include <string>
#include <iostream>

int main(void) {
    sel::State state;
    state["x"] = 0;
    state["y"] = std::string("");

    int x = state["x"];
    int x2 = state["x2"]; // this doesn't exist

    std::string y = state["y"];
    std::string y2 = state["y2"]; // this doesn't exist

    std::cout << (x == x2 ? "same" : "different") << std::endl;
    std::cout << (y == y2 ? "same" : "different") << std::endl;
    return 0;
}
```

```
$ g++-4.9 -std=c++11 -g -I/usr/include/lua5.2 test.cpp -llua5.2 -o test
$ ./test
same
same
$
```

**Comment by ridoncules** [comment]
To deal with this I've been doing:

```
bool exists(sel::Selector selector) {
	std::string str = selector;

	return !(str.compare("") == 0);
}
```

**Comment by ridoncules** [comment]
This doesn't work for booleans though unless you change primitives.h

```
inline std::string _get(_id<std::string>, lua_State *l, const int index) {
	if (lua_isboolean(l, index) == 1) {
		return std::to_string(lua_toboolean(l, index));
	}
	else {
		size_t size;
		const char *buff = lua_tolstring(l, index, &size);
		return std::string{buff, size};
	}
}
```

I might have missed something but I think, along with my previous post, this fixes the problem. In my version of Selene I also have a public getter for `Selector::_name` so that I can print the names of missing variables. The function `bool exists(sel::Selector)` could be named something more appropriate and you could make it into a public member function of `Selector`.

**Comment by mamahuhu** [comment]
I think this feature would be a great addition, whenever one wants to use .lua files as configuration files. 

This would allow the detection of a "missing" value in the configuration file, for which the calling code could take user-defined actions (e.g. if a boolean flag was missing in the configuration file, the calling code could choose to initialize it to whether true or false depending on the desired default behaviour of the software).

**Comment by wileyyugioh** [comment]
If you want to check if a variable exists it is even easier and more universal with lua_isnil.

Just looking at the header for Selector.h, you can add

```
bool exists()
{
    ResetStackOnScopeExit save(_state);
    _traverse();
    _get();

    return lua_isnil(_state, -1);
}

**Comment by adam4813** [comment]
@jeremyong Any chance of getting in @wileyyugioh 's solution ? I can submit a PR but they seem to sort of sit there

**Comment by jeremyong** [comment]
If you submit it I'll accept it. I know I've been an awful maintainer for this project. Life sort of catches up to you in other ways sorry @adam4813

**Comment by adam4813** [comment]
Ok, will get that up later today or tomorrow.

I completely understand how life is more important than pet projects, so don't take my comment as and attempt at being rude/angry please.

**Comment by jeremyong** [comment]
Not at all. I'm genuinely being apologetic and wish I had more time haha
