### ISSUE TITLE
Lua-function called from c++ fires twice in debug-mode

### ISSUE THREAD

**Issue by tkausl** [jeremyong/Selene#63]
Hey there,

i had a little problem, my lua-function fired twice when i compiled in debug-mode (visual studio express 2013). Code to reproduce:
```lua
function ltest()
    print("Hello World");
end
```
```c++
	sel::State state{ true };
	state.Load("test.lua");
	auto ltest = state["ltest"];
	ltest();
```

I figured out, that "named return type optimisation" won't work in debug-mode and since Selector has no move-construktor, it will use the copy-constructor to pass the 'copy' out of the operator(). I fixed this by just creating a small move-constructor for Selector, but since i'm still a beginner in c++ i'm not sure if its the best approach and i don't even know if there is a reason why Selector has no move-constructor so i hope you'll decide what to do with this issue.

**Comment by flaming0** [comment]
Have the same issue. I'm using visual studio 2015 ctp.

**Comment by jeremyong** [comment]
About to work on this now.
