### ISSUE TITLE
Examples of usages with different C++ datatypes

### ISSUE THREAD

**Issue by inDigiNeous** [jeremyong/Selene#64]
Lua newbie here, trying to use this with a simple C++ test project, evaluating use for a bigger project.
Would be useful to have examples of all the datatypes available in Selene.
Sorry if I'm not understanding something, but is there a way to use Selene to pass array (std::array) or raw array [] to lua somehow easily ? 

Or do I have to push it to the stack somehow one value at a time ?
How about std::vector ?

Thanks, this looks good!

**Comment by jeremyong** [comment]
You can pass a pointer or a reference to any type so yea that's fine. See examples where functions accept arguments that are instances of arbitrary classes (like Foo)

**Comment by inDigiNeous** [comment]
Thank you for the answer Jeremy. But I don't understand how to pass a pointer or reference to any type. I understand C++11 fairly well, but started learning Lua this monday, so bear with me.

So I can do this:
```c
	state["printNameTable"]();

	state["name_table"][1] = 11;
	state["name_table"][2] = 12;
	state["name_table"][3] = 13;
	state["name_table"][4] = 14;

	state["printNameTable"]();

	std::array<int, 9> foo = {{ 63, 66, 69, 73, 76, 69, 83, 86, 89 }};
	for (int i=0; i<foo.size(); i++) {
		state["name_table"][i+1] = foo[i];
	}

	state["printNameTable"]();
```

But is there a way to set a table in lua directly by 

```c
  state["name_table"] = foo
```

or 

```c
  int raw[6] = { 1, 2, 3, 5, 7, 9 };
  state["raw_table"] = raw;
```

Or do I have to loop these variables manually and assign index by index ?
How would I assign a pointer to a array, or vector directly to Lua ?
Is this possible even ?

**Comment by jeremyong** [comment]
You need to register the type within Lua first. See the README section on "Registering Classes"
