### ISSUE TITLE
passing std::string ref from lua to c++ function

### ISSUE THREAD

**Issue by badetwiler** [jeremyong/Selene#66]
I'm calling a c++ class member function from lua that has a std::string& argument. Once called an empty string is passed in.  The correct string is passed in if I change the function's argument to accept std::string rather than std::string&. Is there any way around this by registering std::string somehow?

**Comment by jeremyong** [comment]
Can you try changing the function signature to const std::string& and see if it still happens?

**Comment by badetwiler** [comment]
changing the function signature from std::string& to std::string fixes the issue. It happens to be a 3rd partly library I'm trying to wrap, so I was trying to avoid modifying it.  But it's not a huge deal.  Thanks for your quick response.

**Comment by jeremyong** [comment]
Well I think this might be a bug since I am handling functions with parameter type "const std::string &" in a special way. Again, does the adding the `const` qualifier fix it or does the function mutate the string?

**Comment by badetwiler** [comment]
sorry I didn't state this previously; the function argument is specifically "const std::string&". When called from lua I'm seeing just an empty string passed in. Changing the argument to pass by value rather than reference fixes the issue.

**Comment by jeremyong** [comment]
Looks like I have tests for returning strings from class member functions but not sending them :P. Let's leave this open in case I have time to address it and add a new test case. Thanks!

**Comment by badetwiler** [comment]
great, thanks for the help, maybe I'll try sometime as well just to give myself a sanity check
