### ISSUE TITLE
float numbers

### ISSUE THREAD

**Issue by flaming0** [jeremyong/Selene#68]
I noticed that selene uses lua_Number for floating point numbers binding. When LUA_32BIT is not defined lua_Number is double. Is it possible to add float also? For example, casting it to lua_Number.

**Comment by jeremyong** [comment]
The way you would have to do it is to cast explicitly or change the preprocessor definition of lua_Number. The Lua runtime is only compiled with one floating type at a time so that's why this restriction is in place (I don't want to implicitly lower precision for the enduser).
