### ISSUE TITLE
Passing a mutable object to Lua

### ISSUE THREAD

**Issue by DennisOSRM** [jeremyong/Selene#69]
I skip-read the examples, but may have missed it. How would one pass an existing object from C++ into Lua land in a way that it is mutable, i.e. modifiable by a script. 

The use case is the following. We go through a stream of objects that get passed to Lua where a user script is able to modify the object for later use. Right now, we are using LuaBind for that which works ok'ish but is largely unmaintained.

Thanks.

**Comment by jeremyong** [comment]
Register a class and then pass a reference. See https://github.com/jeremyong/Selene/blob/master/test/class_tests.h for examples. It's in the documentation too.
