### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by PhilCK** [jeremyong/Selene#72]
Is Visual Studio 2013 (Update 4) supported at all?

I gave it a shot and it moans about `constexpr` and some other things, have I done something wrong or it VS C++11 just not there?

**Comment by Querijn** [comment]
https://github.com/jeremyong/Selene/issues/47

**Comment by jeremyong** [comment]
Now that VS2015 is out, I'm curious if people have tried that and if it works.

**Comment by Querijn** [comment]
It builds (5.3.1 + pull from just now), required some manual work after CMake generation. 

After running the tests out of the box-ish, it crashes doing the tests:
Exception thrown at 0x012A18B6 in test_runner.exe: 0xC0000005: Access violation reading location 0x00000014.

(Goes somewhat deeper into the code, have to look at it later, gotta run for groceries)
test_runner.exe!test_embedded_nulls(sel::State & state) Line 137	C++
test_runner.exe!ExecuteAll() Line 104	C++
test_runner.exe!main() Line 151	C++
