### ISSUE TITLE
The README specifies "Lua 5.1+" and "Lua 5.2+", which is it?

### ISSUE THREAD

**Issue by stravant** [jeremyong/Selene#73]
Right at the start:
> Simple C++11 friendly header-only bindings to **Lua 5.2+**.

And then in the requirements:
> **Lua 5.1+**

**Comment by LudwikJaniuk** [comment]
[This page](http://lua-users.org/wiki/BindingCodeToLua) suggests 5.2 requirement, and I could not make it build under 5.1, So I guess it's supposed to be 5.2
