### ISSUE TITLE
Float not supported

### ISSUE THREAD

**Issue by bagobor** [jeremyong/Selene#91]
**Sample code:**
```c++
extern "C"
{
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
}

struct SimpleVec2
{
	float x, y;
};

#include <Selene/selene.h>

int main()
{
	sel::State state{ true };
	state["vec2"].SetClass<SimpleVec2>("x", &SimpleVec2::x);
	
  return 0;
}
```

**Comment by jeremyong** [comment]
Can you paste the entire error please? Thanks

**Comment by bagobor** [comment]
https://gist.github.com/bagobor/c97ddf32cc1ae1213c76

**Comment by bagobor** [comment]
It looks like 'float' not supported. :boom::boom:
changing 'float' -> 'int' removes compile errors.

**Comment by bagobor** [comment]
Ok, I found previous issue 
https://github.com/jeremyong/Selene/issues/52

**Comment by bagobor** [comment]
Do I need only provide implementation of:
```c++
inline float _check_get(_id<float>, lua_State *l, const int index) {
	return luaL_checknumber(l, index);
}
```
or also add:
```c++
template <>
struct is_primitive<float> {
	static constexpr bool value = true;
};
```

**Comment by jeremyong** [comment]
The problem is that the internal representation of a floating point number in lua is lua_Number which is a double.

**Comment by bagobor** [comment]
got it ... but it looks weird for luabind switcher. ))

**Comment by jeremyong** [comment]
Lua internally doesn't have more than one floating point representation. If you are ok with float precision, either cast it yourself via an accessor or change the internal representation of lua_Number. The library shouldn't implicitly lose precision for the user IMO.
