### ISSUE TITLE
Add user provided error handling callback

### ISSUE THREAD

**Issue by AnonymousProgrammerLandau** [jeremyong/Selene#95]
I would love to be able to change the error reporting. Logging to std::cout on errors using _print from util.h is not appropriate for my use case. Instead I want to throw Exceptions.
@jeremyong You mentioned to plan [user provided error handling callback](https://github.com/jeremyong/Selene/issues/10#issuecomment-35129649). Do you have any progress or thoughts on that? I offer to work on a Pull Request for that.

**Comment by jeremyong** [comment]
I think such a change would be welcome, provided that there is a build time switch to disable it for those that cannot use exceptions.

**Comment by AnonymousProgrammerLandau** [comment]
What do you exacly mean by being one
> that cannot use exceptions?

I gave it a quick shot by compiling with `-DCMAKE_CXX_FLAGS=-fno-exceptions`. The compiler then points me to `include/selene/State.h:23`. There is a `throw` statement.

**Comment by Zardoz89** [comment]
Also, a way to redefine _print and/or redirect Lua output to a buffer or stream would be nice. Would be nice if Lua output could be write to a logger instead directly to stdout.

**Comment by AnonymousProgrammerLandau** [comment]
Since https://github.com/jeremyong/Selene/commit/4e4a0c577abfa2b479b3c97a5dcbfb2afeae182b that is possible through `sel::State::HandleExceptionsWith(...)`.
