### ISSUE TITLE
Support Visual Studio 2015

### ISSUE THREAD

**Issue by arvidsson** [jeremyong/Selene#99]
I know that it was seemingly impossible to support VS2013. I'm not sure about the exact changes in VS2015 relating to supporting C++ standards, thus my question or wish: would it be possible to support VS2015?

**Comment by Reyfin** [comment]
I have VS 2015 Community and it works with the 140 Compiler.

**Comment by bagobor** [comment]
VS 2015 works totally fine with Selene and lua 5.3.1
My proof:
https://github.com/bagobor/cpp2lua-buindings-battle

Feel free to be more precise (with exact error messages) :+1:

**Comment by arvidsson** [comment]
Ok, I haven't tested it properly in VS2015 yet. I wasn't sure whether support was at all there, since I couldn't find an issue related to it, and I didn't want to waste time switching my project to VS2015.

**Comment by bagobor** [comment]
by the way, you may notice that selene has worstest perfomance (compare to other luabinding libs)

**Comment by jeremyong** [comment]
@bagobor Yes you've already made an entire separate issue addressing that. Honestly, the benchmark just calls a single function that increments a number repeatedly. It's a poor benchmark for a number of reasons, and I've already addressed several. In addition, I've already pointed out an optimization that would make it perform identically to others listed in your benchmark. If you care about the performance to such a degree, just fix it instead of talking about it.

**Comment by bagobor** [comment]
@jeremyong I'm not sure is it right place to discuss it. 
As you may notice - there is 2 selene 'benchcases': a) selene b) selene_cached. 
Second was added for your request to 'optimize' by caching lua state locally.

While dealing with lua - there is only only few most frequent operation - is to call some lua function, call some c-function from lua and get some output values. So my benchmark covered all that. (in a simple way for now). I will be glad to fix any bugs in my test scheme.

**Comment by jeremyong** [comment]
@bagobor If this isn't the right place to discuss it, don't bring it up.
I was referring to #94 which I created specifically to address the performance issue you pointed out.

As for "... there is only only few most frequent operation... " this is entirely subjective. I don't know how you could claim to know what the most typical use case of a user is. In fact, this faulty assumption is usually what the unfortunate majority of benchmark authors possess.

**Comment by bagobor** [comment]
We are talking about layer between c++ and Lua, right?
There is no absolute truth, that's right.
What kind of benchmark will show the true power of Selene?
